// <auto-generated />
using System;
using BookTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookTracker.Data.Migrations
{
    [DbContext(typeof(BookTrackerDbContext))]
    partial class BookTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BookTracker.Core.Entities.AiAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiAuditLogs");
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Andrew Hunt, David Thomas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eric Evans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Frank Herbert"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Patrick Rothfuss"
                        });
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A hands-on guide to the craft of software development. Through dozens of practical tips, it covers writing flexible and maintainable code, avoiding duplication with the DRY principle, using tracer bullets and prototypes, automating with the right tools, and taking pragmatic responsibility for your work. A career-spanning classic for developers who want to think about programming as a craft.",
                            Genre = "Software",
                            Isbn = "9780201616224",
                            Title = "The Pragmatic Programmer",
                            TotalPages = 352
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A manual of software craftsmanship focused on writing code that humans can read. It argues that clean code is a matter of discipline: meaningful names, small functions that do one thing, clear comments only when needed, and rigorous handling of errors and boundaries. Includes detailed case studies that refactor messy code into clean code step by step.",
                            Genre = "Software",
                            Isbn = "9780132350884",
                            Title = "Clean Code",
                            TotalPages = 464
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The foundational text on tackling complexity in software by modeling the business domain. It introduces a shared ubiquitous language between developers and domain experts, and building blocks such as entities, value objects, aggregates, repositories, and bounded contexts. A deep, strategic look at designing software that reflects how a business actually works.",
                            Genre = "Software",
                            Isbn = "9780321125217",
                            Title = "Domain-Driven Design",
                            TotalPages = 560
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Set on the desert planet Arrakis, the only source of the spice melange, this epic follows young Paul Atreides as his family is betrayed and he is drawn into a struggle for control of the planet and its people. A sweeping story of politics, religion, ecology, and prophecy that became one of the most influential science fiction novels ever written.",
                            Genre = "Science Fiction",
                            Isbn = "9780441013593",
                            Title = "Dune",
                            TotalPages = 412
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The first day in the recounted life of Kvothe: a gifted young man who grows up among traveling performers, survives tragedy and poverty, and talks his way into a legendary university of magic. Framed as a memoir told over three days, it is a lyrical coming-of-age fantasy about music, magic, love, and the gap between a legend and the truth behind it.",
                            Genre = "Fantasy",
                            Isbn = "9780756404741",
                            Title = "The Name of the Wind",
                            TotalPages = 662
                        });
                });

            modelBuilder.Entity("BookTracker.Core.Entities.ReadingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FinishedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("ReadingProgress");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CurrentPage = 100,
                            StartedOn = new DateOnly(2025, 1, 5),
                            Status = "Reading"
                        });
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Timeless advice; the tips still hold up.",
                            BookId = 1,
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 5,
                            Reviewer = "Dana"
                        },
                        new
                        {
                            Id = 2,
                            Body = "A few examples feel dated but the principles don't.",
                            BookId = 1,
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 4,
                            Reviewer = "Lee"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Changed how I name things and size functions.",
                            BookId = 2,
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 5,
                            Reviewer = "Sam"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Sweeping world-building — a sci-fi landmark.",
                            BookId = 4,
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 5,
                            Reviewer = "Riley"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Gorgeous prose; a slow but rewarding burn.",
                            BookId = 5,
                            CreatedOn = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 4,
                            Reviewer = "Morgan"
                        });
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Book", b =>
                {
                    b.HasOne("BookTracker.Core.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookTracker.Core.Entities.ReadingProgress", b =>
                {
                    b.HasOne("BookTracker.Core.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Review", b =>
                {
                    b.HasOne("BookTracker.Core.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookTracker.Core.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
